// <auto-generated />
using System;
using Diplom;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diplom.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diplom.Models.Access_Group_Schema_Right", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RightID")
                        .HasColumnType("int");

                    b.Property<int>("SchemeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RightID");

                    b.HasIndex("SchemeID");

                    b.ToTable("Access_Group_Schema_Rights");
                });

            modelBuilder.Entity("Diplom.Models.Access_Right", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Access_Rights");
                });

            modelBuilder.Entity("Diplom.Models.Access_User_Schema_Right", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("RightID")
                        .HasColumnType("int");

                    b.Property<int>("SchemeID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RightID");

                    b.HasIndex("SchemeID");

                    b.ToTable("Access_User_Schema_Rights");
                });

            modelBuilder.Entity("Diplom.Models.Scheme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Schemes");
                });

            modelBuilder.Entity("Diplom.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SchemeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchemeID");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Diplom.Models.Access_Group_Schema_Right", b =>
                {
                    b.HasOne("Diplom.Models.Access_Right", "Access_Right")
                        .WithMany("Access_Group_Schema_Rights")
                        .HasForeignKey("RightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diplom.Models.Scheme", "Scheme")
                        .WithMany("Access_Group_Schema_Rights")
                        .HasForeignKey("SchemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access_Right");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("Diplom.Models.Access_User_Schema_Right", b =>
                {
                    b.HasOne("Diplom.Models.Access_Right", "Access_Right")
                        .WithMany("Access_User_Schema_Rights")
                        .HasForeignKey("RightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diplom.Models.Scheme", "Scheme")
                        .WithMany("Access_User_Schema_Rights")
                        .HasForeignKey("SchemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access_Right");

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("Diplom.Models.Version", b =>
                {
                    b.HasOne("Diplom.Models.Scheme", "Scheme")
                        .WithMany("Versions")
                        .HasForeignKey("SchemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("Diplom.Models.Access_Right", b =>
                {
                    b.Navigation("Access_Group_Schema_Rights");

                    b.Navigation("Access_User_Schema_Rights");
                });

            modelBuilder.Entity("Diplom.Models.Scheme", b =>
                {
                    b.Navigation("Access_Group_Schema_Rights");

                    b.Navigation("Access_User_Schema_Rights");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
